# Generated by Django 4.0.1 on 2022-01-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('answers', models.TextField(verbose_name='Все возможные ответы на вопросы')),
                ('true_answer', models.CharField(max_length=50, verbose_name='Правильный ответ на вопрос')),
            ],
        ),
    ]
