# Generated by Django 3.2.9 on 2022-01-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingWithChangeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('answer1', models.TextField(verbose_name='Первый вариант ответа')),
                ('answer2', models.TextField(verbose_name='Второй вариант ответа')),
                ('answer3', models.TextField(verbose_name='Третий вариант ответа')),
                ('answer4', models.TextField(verbose_name='Четвёртый вариант ответа')),
                ('true_answer', models.CharField(max_length=50, verbose_name='Правильный ответ на вопрос')),
            ],
            options={
                'verbose_name': 'Тестирование',
                'verbose_name_plural': 'Тестирования',
            },
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
    ]
