# Generated by Django 3.2.9 on 2022-01-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_one', '0002_auto_20220123_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingwithchangeanswer',
            name='true_answer',
            field=models.TextField(verbose_name='Правильный ответ на вопрос'),
        ),
    ]
