# Generated by Django 3.2.9 on 2022-01-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_one', '0003_alter_testingwithchangeanswer_true_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingwithchangeanswer',
            name='answer1',
            field=models.CharField(max_length=250, verbose_name='Первый вариант ответа'),
        ),
        migrations.AlterField(
            model_name='testingwithchangeanswer',
            name='answer2',
            field=models.CharField(max_length=250, verbose_name='Второй вариант ответа'),
        ),
        migrations.AlterField(
            model_name='testingwithchangeanswer',
            name='answer3',
            field=models.CharField(max_length=250, verbose_name='Третий вариант ответа'),
        ),
        migrations.AlterField(
            model_name='testingwithchangeanswer',
            name='answer4',
            field=models.CharField(max_length=250, verbose_name='Четвёртый вариант ответа'),
        ),
        migrations.AlterField(
            model_name='testingwithchangeanswer',
            name='question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='testingwithchangeanswer',
            name='true_answer',
            field=models.CharField(max_length=250, verbose_name='Правильный ответ на вопрос'),
        ),
    ]
